project:
  type: website

website:
  title: "CWD-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rochellerafn
      - icon: linkedin
        href: https://linkedin.com/in/rochellerafn
format:
  html:
    theme: lux
    css: styles.css



