---
title: "Archive-Product-Mix-2017-2019"
author: "Rochelle Rafn"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```


```{r}
archive_mix_2017_01 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-01.csv")
archive_mix_2017_02 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-02.csv")
archive_mix_2017_03 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-03.csv")
archive_mix_2017_04 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-04.csv")
archive_mix_2017_05 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-05.csv")
archive_mix_2017_06 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-06.csv")
archive_mix_2017_07 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-07.csv")
archive_mix_2017_08 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-08.csv")
archive_mix_2017_09 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-09.csv")
archive_mix_2017_10 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-10.csv")
archive_mix_2017_11 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-11.csv")
archive_mix_2017_12 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2017-12.csv")

archive_mix_2018_01 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-01.csv")
archive_mix_2018_02 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-02.csv")
archive_mix_2018_03 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-03.csv")
archive_mix_2018_04 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-04.csv")
archive_mix_2018_05 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-05.csv")
archive_mix_2018_06 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-06.csv")
archive_mix_2018_07 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-07.csv")
archive_mix_2018_08 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-08.csv")
archive_mix_2018_09 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-09.csv")
archive_mix_2018_10 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-10.csv")
archive_mix_2018_11 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-11.csv")
archive_mix_2018_12 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2018-12.csv")

archive_mix_2019_01 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-01.csv")
archive_mix_2019_02 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-02.csv")
archive_mix_2019_03 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-03.csv")
archive_mix_2019_04 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-04.csv")
archive_mix_2019_05 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-05.csv")
archive_mix_2019_06 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-06.csv")
archive_mix_2019_07 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-07.csv")
archive_mix_2019_08 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-08.csv")
archive_mix_2019_09 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-09.csv")
archive_mix_2019_10 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-10.csv")
archive_mix_2019_11 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-11.csv")
archive_mix_2019_12 <- read.csv("/Users/rochellerafn/RStudio_Files/Archive_Coffee_Bar/Product_Mix_2019-12.csv")
```


```{r}
str(archive_mix_2017_12)
```

### 2017

```{r}
Year = 2017
Month = "January"

archive_mix_2017_01 <- cbind(archive_mix_2017_01, Year, Month)

head(archive_mix_2017_01)
```

```{r}
Year = 2017
Month = "February"

archive_mix_2017_02 <- cbind(archive_mix_2017_02, Year, Month)

head(archive_mix_2017_02)
```

```{r}
Year = 2017
Month = "March"

archive_mix_2017_03 <- cbind(archive_mix_2017_03, Year, Month)

head(archive_mix_2017_03)
```

```{r}
Year = 2017
Month = "April"

archive_mix_2017_04 <- cbind(archive_mix_2017_04, Year, Month)

head(archive_mix_2017_04)
```

```{r}
Year = 2017
Month = "May"

archive_mix_2017_05 <- cbind(archive_mix_2017_05, Year, Month)

archive_mix_2017_05 <- archive_mix_2017_05[,-13]

head(archive_mix_2017_05)
```

```{r}
Year = 2017
Month = "June"

archive_mix_2017_06 <- cbind(archive_mix_2017_06, Year, Month)

head(archive_mix_2017_06)
```

```{r}
Year = 2017
Month = "July"

archive_mix_2017_07 <- cbind(archive_mix_2017_07, Year, Month)

head(archive_mix_2017_07)
```

```{r}
Year = 2017
Month = "August"

archive_mix_2017_08 <- cbind(archive_mix_2017_08, Year, Month)

head(archive_mix_2017_08)
```

```{r}
Year = 2017
Month = "September"

archive_mix_2017_09 <- cbind(archive_mix_2017_09, Year, Month)

head(archive_mix_2017_09)
```

```{r}
Year = 2017
Month = "October"

archive_mix_2017_10 <- cbind(archive_mix_2017_10, Year, Month)

head(archive_mix_2017_10)
```

```{r}
Year = 2017
Month = "November"

archive_mix_2017_11 <- cbind(archive_mix_2017_11, Year, Month)

head(archive_mix_2017_11)
```

```{r}
Year = 2017
Month = "December"

archive_mix_2017_12 <- cbind(archive_mix_2017_12, Year, Month)

head(archive_mix_2017_12)
```

### 2018

```{r}
Year = 2018
Month = "January"

archive_mix_2018_01 <- cbind(archive_mix_2018_01, Year, Month)

head(archive_mix_2018_01)
```

```{r}
Year = 2018
Month = "February"

archive_mix_2018_02 <- cbind(archive_mix_2018_02, Year, Month)

head(archive_mix_2018_02)
```

```{r}
Year = 2018
Month = "March"

archive_mix_2018_03 <- cbind(archive_mix_2018_03, Year, Month)

head(archive_mix_2018_03)
```

```{r}
Year = 2018
Month = "April"

archive_mix_2018_04 <- cbind(archive_mix_2018_04, Year, Month)

head(archive_mix_2018_04)
```

```{r}
Year = 2018
Month = "May"

archive_mix_2018_05 <- cbind(archive_mix_2018_05, Year, Month)

head(archive_mix_2018_05)
```

```{r}
Year = 2018
Month = "June"

archive_mix_2018_06 <- cbind(archive_mix_2018_06, Year, Month)

head(archive_mix_2018_06)
```

```{r}
Year = 2018
Month = "July"

archive_mix_2018_07 <- cbind(archive_mix_2018_07, Year, Month)

head(archive_mix_2018_07)
```

```{r}
Year = 2018
Month = "August"

archive_mix_2018_08 <- cbind(archive_mix_2018_08, Year, Month)

head(archive_mix_2018_08)
```

```{r}
Year = 2018
Month = "September"

archive_mix_2018_09 <- cbind(archive_mix_2018_09, Year, Month)

head(archive_mix_2018_09)
```

```{r}
Year = 2018
Month = "October"

archive_mix_2018_10 <- cbind(archive_mix_2018_10, Year, Month)

head(archive_mix_2018_10)
```

```{r}
Year = 2018
Month = "November"

archive_mix_2018_11 <- cbind(archive_mix_2018_11, Year, Month)

head(archive_mix_2018_11)
```

```{r}
Year = 2018
Month = "December"

archive_mix_2018_12 <- cbind(archive_mix_2018_12, Year, Month)

head(archive_mix_2018_12)
```


### 2019

```{r}
Year = 2019
Month = "January"

archive_mix_2019_01 <- cbind(archive_mix_2019_01, Year, Month)

head(archive_mix_2019_01)
```

```{r}
Year = 2019
Month = "February"

archive_mix_2019_02 <- cbind(archive_mix_2019_02, Year, Month)

head(archive_mix_2019_02)
```

```{r}
Year = 2019
Month = "March"

archive_mix_2019_03 <- cbind(archive_mix_2019_03, Year, Month)

head(archive_mix_2019_03)
```

```{r}
Year = 2019
Month = "April"

archive_mix_2019_04 <- cbind(archive_mix_2019_04, Year, Month)

head(archive_mix_2019_04)
```

```{r}
Year = 2019
Month = "May"

archive_mix_2019_05 <- cbind(archive_mix_2019_05, Year, Month)

head(archive_mix_2019_05)
```

```{r}
Year = 2019
Month = "June"

archive_mix_2019_06 <- cbind(archive_mix_2019_06, Year, Month)

head(archive_mix_2019_06)
```

```{r}
Year = 2019
Month = "July"

archive_mix_2019_07 <- cbind(archive_mix_2019_07, Year, Month)

head(archive_mix_2019_07)
```

```{r}
Year = 2019
Month = "August"

archive_mix_2019_08 <- cbind(archive_mix_2019_08, Year, Month)

head(archive_mix_2019_08)
```

```{r}
Year = 2019
Month = "September"

archive_mix_2019_09 <- cbind(archive_mix_2019_09, Year, Month)

head(archive_mix_2019_09)
```

```{r}
Year = 2019
Month = "October"

archive_mix_2019_10 <- cbind(archive_mix_2019_10, Year, Month)

head(archive_mix_2019_10)
```

```{r}
Year = 2019
Month = "November"

archive_mix_2019_11 <- cbind(archive_mix_2019_11, Year, Month)

head(archive_mix_2019_11)
```

```{r}
Year = 2019
Month = "December"

archive_mix_2019_12 <- cbind(archive_mix_2019_12, Year, Month)

head(archive_mix_2019_12)
```


### Merging Months

```{r}
archive_mix_2017_ALL <- rbind(archive_mix_2017_01, archive_mix_2017_02, archive_mix_2017_03, archive_mix_2017_04, archive_mix_2017_05, archive_mix_2017_06, archive_mix_2017_07, archive_mix_2017_08, archive_mix_2017_09, archive_mix_2017_10, archive_mix_2017_11, archive_mix_2017_12)

archive_mix_2017_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Total))
archive_mix_2017_ALL$Gross.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Gross.Revenue))
archive_mix_2017_ALL$Discounts <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Discounts))
archive_mix_2017_ALL$Refund <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Refund))
archive_mix_2017_ALL$Net.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Net.Revenue))
archive_mix_2017_ALL$Cost <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Cost))
archive_mix_2017_ALL$Profitability <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Profitability))
archive_mix_2017_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2017_ALL$Total))

archive_mix_2017_ALL <- archive_mix_2017_ALL %>%
mutate(Year = as.character("2017"), Month = factor(Month, levels = month.name))

sapply(archive_mix_2017_ALL, function(x) sum(is.na(x)))

head(archive_mix_2017_ALL)

archive_mix_2017_ALL %>%
  group_by(Month) %>%
  summarise(Total = sum(Total))
```


```{r}
archive_mix_2018_ALL <- rbind(archive_mix_2018_01, archive_mix_2018_02, archive_mix_2018_03, archive_mix_2018_04, archive_mix_2018_05, archive_mix_2018_06, archive_mix_2018_07, archive_mix_2018_08, archive_mix_2018_09, archive_mix_2018_10, archive_mix_2018_11, archive_mix_2018_12)

archive_mix_2018_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Total))
archive_mix_2018_ALL$Gross.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Gross.Revenue))
archive_mix_2018_ALL$Discounts <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Discounts))
archive_mix_2018_ALL$Refund <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Refund))
archive_mix_2018_ALL$Net.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Net.Revenue))
archive_mix_2018_ALL$Cost <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Cost))
archive_mix_2018_ALL$Profitability <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Profitability))
archive_mix_2018_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2018_ALL$Total))
archive_mix_2018_ALL$Year <- as.character(archive_mix_2018_ALL$Year)

archive_mix_2018_ALL <- archive_mix_2018_ALL %>%
mutate(Year = as.character("2018"), Month = factor(Month, levels = month.name))

sapply(archive_mix_2018_ALL, function(x) sum(is.na(x)))

head(archive_mix_2018_ALL)

archive_mix_2018_ALL %>%
  group_by(Month) %>%
  summarise(Total = sum(Total))
```

```{r}
archive_mix_2019_ALL <- rbind(archive_mix_2019_01, archive_mix_2019_02, archive_mix_2019_03, archive_mix_2019_04, archive_mix_2019_05, archive_mix_2019_06, archive_mix_2019_07, archive_mix_2019_08, archive_mix_2019_09, archive_mix_2019_10, archive_mix_2019_11, archive_mix_2019_12)

archive_mix_2019_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Total))
archive_mix_2019_ALL$Gross.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Gross.Revenue))
archive_mix_2019_ALL$Discounts <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Discounts))
archive_mix_2019_ALL$Refund <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Refund))
archive_mix_2019_ALL$Net.Revenue <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Net.Revenue))
archive_mix_2019_ALL$Cost <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Cost))
archive_mix_2019_ALL$Profitability <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Profitability))
archive_mix_2019_ALL$Total <- as.numeric(gsub("[^0-9.]", "", archive_mix_2019_ALL$Total))
archive_mix_2019_ALL$Year <- as.character(archive_mix_2019_ALL$Year)

archive_mix_2019_ALL <- archive_mix_2019_ALL %>%
mutate(Year = as.character("2019"), Month = factor(Month, levels = month.name))

sapply(archive_mix_2018_ALL, function(x) sum(is.na(x)))

head(archive_mix_2019_ALL)

archive_mix_2019_ALL %>%
  group_by(Month) %>%
  summarise(Total = sum(Total))
```

### Total Sales By Month By Year

```{r}
archive_monthly_mix_2017 <- archive_mix_2017_ALL%>%
  group_by(Month) %>%
  summarise(Total=sum(Total))

archive_monthly_mix_2017 <- archive_monthly_mix_2017 %>%
  mutate(Year = as.character("2017"))

archive_monthly_mix_2017 %>%
  arrange(Month, Year)
```

```{r}
archive_monthly_mix_2018 <- archive_mix_2018_ALL%>%
  group_by(Month) %>%
  summarise(Total=sum(Total))

archive_monthly_mix_2018 <- archive_monthly_mix_2018 %>%
  mutate(Year = as.character("2018"))

archive_monthly_mix_2018 %>%
  arrange(Month, Year)
```


```{r}
archive_monthly_mix_2019 <- archive_mix_2019_ALL%>%
  group_by(Month) %>%
  summarise(Total=sum(Total))

archive_monthly_mix_2019 <- archive_monthly_mix_2019 %>%
  mutate(Year = as.character("2019"))

archive_monthly_mix_2019 %>%
  arrange(Month, Year)
```

```{r}
archive_monthly_mix_ALL <- rbind(archive_monthly_mix_2019, archive_monthly_mix_2018, archive_monthly_mix_2017) 

archive_monthly_mix_ALL %>%
  arrange(Month, Year)
```

```{r}
ggplot(archive_monthly_mix_ALL, aes(Month, Total, group=Year, color=Year))+
  geom_point() +
  geom_line(size=.7) +
  theme(panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```


### Merging Years

```{r}
archive_mix_2017_2019_ALL <- rbind(archive_mix_2017_ALL, archive_mix_2018_ALL, archive_mix_2019_ALL)

str(archive_mix_2017_2019_ALL)
```

```{r}
unique(archive_mix_2017_2019_ALL$Total)
```

```{r}
head(archive_mix_2017_2019_ALL)
```


