---
title: "OR Liquor County Sales Repository"
author: "Rochelle Rafn"
date: "04/16/2023"
categories: [code]
format: 
   html:
     code-fold: true
     code-summary: "Show Code"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
```

#### Creating a function for a parameterized markdown
This function will replicate a report that I made in markdown based on the parameters I set. In this case, I created a table and visualization of the yearly sales for a county. All of the information the parameters are pulling from is listed below. An example output file is in my next post.

```{r}
library(tidyverse)
library(rmarkdown)
library(purrr)

county_liquor_sales <- function(x) {
  render("OR_County_Parameters.qmd", 
         params = list(county = x), 
         output_file = paste0("/Users/rochellerafn/RStudio_Files/Data_Communication/CWD-Blog/posts/or-liquor-analysis-2/county_files/",x,".html"))
}

or_county_sales <- read.csv("/Users/rochellerafn/RStudio_Files/Data_Communication/CWD-Blog/or_county_sales.csv")

or_county_sales <- or_county_sales %>%
  select(-Month, -X) %>%
  group_by(COUNTY, Year) %>%
  rename("County" = "COUNTY") %>%
  summarize(sum(Total.Sales)) %>%
  rename("Total.Sales" = "sum(Total.Sales)")

or_county_sales$COUNTY %>% map(., function(x) { county_liquor_sales(x)})
```

 
 

## County Liquor Sales

```{r}
library(DT)


or_county_sales <- read.csv("/Users/rochellerafn/RStudio_Files/Data_Communication/CWD-Blog/or_county_sales.csv")

or_county_sales <- or_county_sales %>%
  select(-Month, -X) %>%
  group_by(COUNTY, Year) %>%
  rename("County" = "COUNTY") %>%
  summarize(sum(Total.Sales)) %>%
  rename("Total.Sales" = "sum(Total.Sales)")

datatable(or_county_sales)
```

